name: Trigger CI on Push

on:
  push:
    branches:
      - main

jobs:
  trigger-ci:
    runs-on: ubuntu-latest

    steps:
      - name: 📦 Checkout code
        uses: actions/checkout@v3

      - name: 🔓 Make scripts executable
        run: chmod +x scripts/*.sh

      - name: 💽 Check disk usage
        run: ./scripts/check_disk.sh
        
      - name: Trigger CI Workflow 10 times via API
        env:
          REPO: ${{ github.repository }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./scripts/trigger_start_project.sh
